#ifndef DEM_CFG_H
#define DEM_CFG_H

#include "Dem.h"

/* DTC code table - all 15 railway fault events */
static const Dem_EventCfgType Dem_EventCfgTable[DEM_NUM_EVENTS] =
{
    /* eventId                       dtc        severity            debounceType        */
    { RAIL_EVT_BRAKE_SENSORLOSS,   0x010101U, DEM_SEVERITY_HIGH,   DEM_DEBOUNCE_COUNTER },
    { RAIL_EVT_DOOR_LOCKFAIL,      0x010201U, DEM_SEVERITY_HIGH,   DEM_DEBOUNCE_COUNTER },
    { RAIL_EVT_TEMP_OVERTEMP,      0x010301U, DEM_SEVERITY_MEDIUM, DEM_DEBOUNCE_TIME    },
    { RAIL_EVT_MOTOR_OVERCURRENT,  0x010401U, DEM_SEVERITY_HIGH,   DEM_DEBOUNCE_COUNTER },
    { RAIL_EVT_CAN_TIMEOUT,        0x010501U, DEM_SEVERITY_MEDIUM, DEM_DEBOUNCE_COUNTER },
    { RAIL_EVT_SIGNAL_LOSS,        0x010601U, DEM_SEVERITY_MEDIUM, DEM_DEBOUNCE_TIME    },
    { RAIL_EVT_HVAC_FAIL,          0x010701U, DEM_SEVERITY_LOW,    DEM_DEBOUNCE_COUNTER },
    { RAIL_EVT_POWER_UNDERVOLT,    0x010801U, DEM_SEVERITY_HIGH,   DEM_DEBOUNCE_COUNTER },
    { RAIL_EVT_BRAKE_PRESSURE_LOW, 0x010901U, DEM_SEVERITY_HIGH,   DEM_DEBOUNCE_COUNTER },
    { RAIL_EVT_DOOR_OPEN_SPEED,    0x010A01U, DEM_SEVERITY_HIGH,   DEM_DEBOUNCE_COUNTER },
    { RAIL_EVT_MOTOR_STALL,        0x010B01U, DEM_SEVERITY_MEDIUM, DEM_DEBOUNCE_TIME    },
    { RAIL_EVT_CAN_BUS_OFF,        0x010C01U, DEM_SEVERITY_HIGH,   DEM_DEBOUNCE_COUNTER },
    { RAIL_EVT_ETH_LINK_DOWN,      0x010D01U, DEM_SEVERITY_MEDIUM, DEM_DEBOUNCE_COUNTER },
    { RAIL_EVT_ETH_TIMEOUT,        0x010E01U, DEM_SEVERITY_MEDIUM, DEM_DEBOUNCE_TIME    },
    { RAIL_EVT_SPEED_SENSOR_FAIL,  0x010F01U, DEM_SEVERITY_HIGH,   DEM_DEBOUNCE_COUNTER },
};

#endif /* DEM_CFG_H */