#ifndef DEM_CFG_H
#define DEM_CFG_H

#include "Dem.h"

/* DTC table for all 19 Kavach events */
static const Dem_EventCfgType Dem_EventCfgTable[DEM_NUM_EVENTS] =
{
    /* Kavach Mode Events */
    { KAVACH_EVT_MODE_SB,   0x010101U, DEM_SEVERITY_LOW,    DEM_DEBOUNCE_COUNTER },
    { KAVACH_EVT_MODE_FS,   0x010201U, DEM_SEVERITY_LOW,    DEM_DEBOUNCE_COUNTER },
    { KAVACH_EVT_MODE_LS,   0x010301U, DEM_SEVERITY_MEDIUM, DEM_DEBOUNCE_COUNTER },
    { KAVACH_EVT_MODE_SR,   0x010401U, DEM_SEVERITY_MEDIUM, DEM_DEBOUNCE_COUNTER },
    { KAVACH_EVT_MODE_SH,   0x010501U, DEM_SEVERITY_MEDIUM, DEM_DEBOUNCE_COUNTER },
    { KAVACH_EVT_MODE_OS,   0x010601U, DEM_SEVERITY_HIGH,   DEM_DEBOUNCE_COUNTER },
    { KAVACH_EVT_MODE_TR,   0x010701U, DEM_SEVERITY_HIGH,   DEM_DEBOUNCE_COUNTER },
    { KAVACH_EVT_MODE_PT,   0x010801U, DEM_SEVERITY_HIGH,   DEM_DEBOUNCE_COUNTER },
    { KAVACH_EVT_MODE_RV,   0x010901U, DEM_SEVERITY_MEDIUM, DEM_DEBOUNCE_COUNTER },
    { KAVACH_EVT_MODE_SF,   0x010F01U, DEM_SEVERITY_HIGH,   DEM_DEBOUNCE_COUNTER },

    /* Kavach Critical Safety Events */
    { KAVACH_EVT_OVERSPEED, 0x00A101U, DEM_SEVERITY_HIGH,   DEM_DEBOUNCE_COUNTER },
    { KAVACH_EVT_SPAD,      0x00A201U, DEM_SEVERITY_HIGH,   DEM_DEBOUNCE_COUNTER },
    { KAVACH_EVT_SOS,       0x00A301U, DEM_SEVERITY_HIGH,   DEM_DEBOUNCE_COUNTER },
    { KAVACH_EVT_ROLLBACK,  0x00A401U, DEM_SEVERITY_HIGH,   DEM_DEBOUNCE_COUNTER },
    { KAVACH_EVT_RADIO_LOSS,0x00A501U, DEM_SEVERITY_MEDIUM, DEM_DEBOUNCE_TIME    },
    { KAVACH_EVT_BRAKE_CMD, 0x00A601U, DEM_SEVERITY_HIGH,   DEM_DEBOUNCE_COUNTER },

    /* Kavach Info Events */
    { KAVACH_EVT_RFID,      0x00B101U, DEM_SEVERITY_LOW,    DEM_DEBOUNCE_COUNTER },
    { KAVACH_EVT_SIG,       0x00B201U, DEM_SEVERITY_LOW,    DEM_DEBOUNCE_COUNTER },
    { KAVACH_EVT_MA,        0x00B301U, DEM_SEVERITY_LOW,    DEM_DEBOUNCE_COUNTER },
};

#endif /* DEM_CFG_H */
